// <auto-generated />
using System;
using Exam.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam.Infraestucture.Migrations
{
    [DbContext(typeof(ExamContext))]
    partial class ExamContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Exam.Domain.Entities.Location", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("City");

                    b.Property<string>("PostCode");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.HasKey("UserId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Exam.Domain.Entities.User", b =>
                {
                    b.Property<string>("IdValue")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email");

                    b.Property<string>("Gender");

                    b.Property<string>("Name");

                    b.Property<string>("UserName");

                    b.Property<string>("Uuid");

                    b.HasKey("IdValue");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Exam.Domain.Entities.Location", b =>
                {
                    b.HasOne("Exam.Domain.Entities.User", "User")
                        .WithOne("Location")
                        .HasForeignKey("Exam.Domain.Entities.Location", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
